// Code generated by goshtoso iconpack. DO NOT EDIT.
// Release: iconpack-77e5cb96fdde
// Catalog SHA-256: 77e5cb96fdde8f293384e2897a47890f02f0ba3cb4298e3f014566dbce754020

package appicons

import "github.com/araihu/goshtoso/components/icon"

type Name string

type Glyph struct {
	Name          Name
	CanonicalName string
	Namespace     string
	Product       string
	Symbol        icon.Symbol
	ColorBehavior string
}

type Config struct {
	Symbol     icon.Symbol
	Size       icon.Size
	Label      string
	Decorative bool
	RootClass  string
}

const SpriteURL = "/ui/icons/sprite.svg"

const (
	NameKubernetesKubernetes Name        = "kubernetes-kubernetes"
	IconKubernetesKubernetes icon.Symbol = "kubernetes-kubernetes"
)

var Glyphs = []Glyph{
	{Name: NameKubernetesKubernetes, CanonicalName: "kubernetes-kubernetes", Namespace: "custom", Product: "kubernetes", Symbol: IconKubernetesKubernetes, ColorBehavior: "currentColor"},
}

func Lookup(name Name) (Glyph, bool) {
	for _, glyph := range Glyphs {
		if glyph.Name == name {
			return glyph, true
		}
	}
	return Glyph{}, false
}

func Icon(cfg Config) icon.Instance {
	return icon.Icon(icon.Config{SpriteURL: SpriteURL, Symbol: cfg.Symbol, Size: cfg.Size, Label: cfg.Label, Decorative: cfg.Decorative, RootClass: cfg.RootClass})
}
