apiVersion: v1
kind: ServiceAccount
metadata:
  name: balemoh-discoverer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: balemoh-discoverer
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: balemoh-discoverer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: balemoh-discoverer
subjects:
- kind: ServiceAccount
  name: balemoh-discoverer
