// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteServiceEndpoints = `-- name: DeleteServiceEndpoints :exec
DELETE FROM service_endpoints
WHERE service_id = ?1
`

func (q *Queries) DeleteServiceEndpoints(ctx context.Context, serviceID string) error {
	_, err := q.db.ExecContext(ctx, deleteServiceEndpoints, serviceID)
	return err
}

const getDiscoveredService = `-- name: GetDiscoveredService :one
SELECT
    id,
    source_kind,
    source_id,
    resource_kind,
    resource_namespace,
    resource_name,
    display_name,
    description,
    metadata_json,
    observed_at,
    pinned_at,
    created_at,
    updated_at
FROM discovered_services
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetDiscoveredService(ctx context.Context, id string) (DiscoveredService, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveredService, id)
	var i DiscoveredService
	err := row.Scan(
		&i.ID,
		&i.SourceKind,
		&i.SourceID,
		&i.ResourceKind,
		&i.ResourceNamespace,
		&i.ResourceName,
		&i.DisplayName,
		&i.Description,
		&i.MetadataJson,
		&i.ObservedAt,
		&i.PinnedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertServiceEndpoint = `-- name: InsertServiceEndpoint :exec
INSERT INTO service_endpoints (
    service_id,
    name,
    url,
    port,
    protocol,
    provenance
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type InsertServiceEndpointParams struct {
	ServiceID  string `json:"service_id"`
	Name       string `json:"name"`
	Url        string `json:"url"`
	Port       int64  `json:"port"`
	Protocol   string `json:"protocol"`
	Provenance string `json:"provenance"`
}

func (q *Queries) InsertServiceEndpoint(ctx context.Context, arg InsertServiceEndpointParams) error {
	_, err := q.db.ExecContext(ctx, insertServiceEndpoint,
		arg.ServiceID,
		arg.Name,
		arg.Url,
		arg.Port,
		arg.Protocol,
		arg.Provenance,
	)
	return err
}

const listDiscoveredServices = `-- name: ListDiscoveredServices :many
SELECT
    id,
    source_kind,
    source_id,
    resource_kind,
    resource_namespace,
    resource_name,
    display_name,
    description,
    metadata_json,
    observed_at,
    pinned_at,
    created_at,
    updated_at
FROM discovered_services
ORDER BY lower(display_name), id
`

func (q *Queries) ListDiscoveredServices(ctx context.Context) ([]DiscoveredService, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveredServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveredService
	for rows.Next() {
		var i DiscoveredService
		if err := rows.Scan(
			&i.ID,
			&i.SourceKind,
			&i.SourceID,
			&i.ResourceKind,
			&i.ResourceNamespace,
			&i.ResourceName,
			&i.DisplayName,
			&i.Description,
			&i.MetadataJson,
			&i.ObservedAt,
			&i.PinnedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedDiscoveredServices = `-- name: ListPinnedDiscoveredServices :many
SELECT
    id,
    source_kind,
    source_id,
    resource_kind,
    resource_namespace,
    resource_name,
    display_name,
    description,
    metadata_json,
    observed_at,
    pinned_at,
    created_at,
    updated_at
FROM discovered_services
WHERE pinned_at IS NOT NULL
ORDER BY lower(display_name), id
`

func (q *Queries) ListPinnedDiscoveredServices(ctx context.Context) ([]DiscoveredService, error) {
	rows, err := q.db.QueryContext(ctx, listPinnedDiscoveredServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveredService
	for rows.Next() {
		var i DiscoveredService
		if err := rows.Scan(
			&i.ID,
			&i.SourceKind,
			&i.SourceID,
			&i.ResourceKind,
			&i.ResourceNamespace,
			&i.ResourceName,
			&i.DisplayName,
			&i.Description,
			&i.MetadataJson,
			&i.ObservedAt,
			&i.PinnedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceEndpoints = `-- name: ListServiceEndpoints :many
SELECT
    id,
    service_id,
    name,
    url,
    port,
    protocol,
    provenance
FROM service_endpoints
WHERE service_id = ?1
ORDER BY id
`

func (q *Queries) ListServiceEndpoints(ctx context.Context, serviceID string) ([]ServiceEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listServiceEndpoints, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceEndpoint
	for rows.Next() {
		var i ServiceEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Url,
			&i.Port,
			&i.Protocol,
			&i.Provenance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinDiscoveredService = `-- name: PinDiscoveredService :execrows
UPDATE discovered_services
SET pinned_at = ?1,
    updated_at = ?2
WHERE id = ?3
`

type PinDiscoveredServiceParams struct {
	PinnedAt  sql.NullString `json:"pinned_at"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) PinDiscoveredService(ctx context.Context, arg PinDiscoveredServiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pinDiscoveredService, arg.PinnedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unpinDiscoveredService = `-- name: UnpinDiscoveredService :execrows
UPDATE discovered_services
SET pinned_at = NULL,
    updated_at = ?1
WHERE id = ?2
`

type UnpinDiscoveredServiceParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UnpinDiscoveredService(ctx context.Context, arg UnpinDiscoveredServiceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unpinDiscoveredService, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertDiscoveredService = `-- name: UpsertDiscoveredService :exec
INSERT INTO discovered_services (
    id,
    source_kind,
    source_id,
    resource_kind,
    resource_namespace,
    resource_name,
    display_name,
    description,
    metadata_json,
    observed_at,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12
)
ON CONFLICT (id) DO UPDATE SET
    source_kind = excluded.source_kind,
    source_id = excluded.source_id,
    resource_kind = excluded.resource_kind,
    resource_namespace = excluded.resource_namespace,
    resource_name = excluded.resource_name,
    display_name = excluded.display_name,
    description = excluded.description,
    metadata_json = excluded.metadata_json,
    observed_at = excluded.observed_at,
    updated_at = excluded.updated_at
`

type UpsertDiscoveredServiceParams struct {
	ID                string `json:"id"`
	SourceKind        string `json:"source_kind"`
	SourceID          string `json:"source_id"`
	ResourceKind      string `json:"resource_kind"`
	ResourceNamespace string `json:"resource_namespace"`
	ResourceName      string `json:"resource_name"`
	DisplayName       string `json:"display_name"`
	Description       string `json:"description"`
	MetadataJson      string `json:"metadata_json"`
	ObservedAt        string `json:"observed_at"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) UpsertDiscoveredService(ctx context.Context, arg UpsertDiscoveredServiceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscoveredService,
		arg.ID,
		arg.SourceKind,
		arg.SourceID,
		arg.ResourceKind,
		arg.ResourceNamespace,
		arg.ResourceName,
		arg.DisplayName,
		arg.Description,
		arg.MetadataJson,
		arg.ObservedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
