schemaVersion: 1
sources:
  - id: kubernetes
    kind: file
    url: https://raw.githubusercontent.com/devicons/devicon/54cfe13ac10eaa1ef817a343ab0a9437eb3c2e08/icons/kubernetes/kubernetes-plain.svg
    path: kubernetes.svg
    license: MIT
    licensePath: LICENSE
    licenseUrl: https://raw.githubusercontent.com/devicons/devicon/54cfe13ac10eaa1ef817a343ab0a9437eb3c2e08/LICENSE
